"""empty message

Revision ID: d36baf918a3b
Revises: 
Create Date: 2019-03-06 18:49:38.628065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36baf918a3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('s12', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s13', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s14', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s15', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s21', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s22', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s23', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s24', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s25', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s31', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s32', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s33', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s34', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s35', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s41', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s42', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s43', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s44', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s45', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s51', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s52', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s53', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s54', sa.String(length=6), nullable=True))
    op.add_column('card', sa.Column('s55', sa.String(length=6), nullable=True))
    op.create_foreign_key(None, 'card', 'square', ['s54'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s31'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s34'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s21'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s43'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s14'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s52'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s45'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s23'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s33'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s41'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s42'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s12'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s32'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s22'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s55'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s15'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s35'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s44'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s53'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s25'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s24'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s51'], ['id'])
    op.create_foreign_key(None, 'card', 'square', ['s13'], ['id'])
    op.create_foreign_key(None, 'user', 'room', ['roomid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 's55')
    op.drop_column('card', 's54')
    op.drop_column('card', 's53')
    op.drop_column('card', 's52')
    op.drop_column('card', 's51')
    op.drop_column('card', 's45')
    op.drop_column('card', 's44')
    op.drop_column('card', 's43')
    op.drop_column('card', 's42')
    op.drop_column('card', 's41')
    op.drop_column('card', 's35')
    op.drop_column('card', 's34')
    op.drop_column('card', 's33')
    op.drop_column('card', 's32')
    op.drop_column('card', 's31')
    op.drop_column('card', 's25')
    op.drop_column('card', 's24')
    op.drop_column('card', 's23')
    op.drop_column('card', 's22')
    op.drop_column('card', 's21')
    op.drop_column('card', 's15')
    op.drop_column('card', 's14')
    op.drop_column('card', 's13')
    op.drop_column('card', 's12')
    # ### end Alembic commands ###
